<?php
namespace PueueJobDispatcher\Form;

use Laminas\Form\Element;
use Laminas\Form\Form;
use Laminas\I18n\Translator\TranslatorAwareTrait;
use Laminas\I18n\Translator\TranslatorAwareInterface;

class ConfigForm extends Form implements TranslatorAwareInterface
{
    use TranslatorAwareTrait;


    public function init()
    {
        $this->setAttribute('id', 'config-form');

        $this->add([
            'name' => 'pueue_enabled',
            'type' => Element\Checkbox::class,
            'options' => [
                'label' => "Enable Pueue as default job dispatcher", // @translate
                'info' => "If checked, all command line jobs will be handled by Pueue.", // @translate
            ],
            'attributes' => [
                'id' => 'pueue_enabled',
            ],
        ]);

        $this->add([
            'name' => 'pueue_path',
            'type' => Element\Text::class,
            'options' => [
                'label' => "Pueue client path", //@translate
                'info' => "Optional path to the pueue client",
            ],
            'attributes' => [
                'id' => 'pueue_group',
                'required' => false,
            ],
        ]);

        $this->add([
            'name' => 'pueue_group',
            'type' => Element\Text::class,
            'options' => [
                'label' => "Pueue job group (default group if empty)", //@translate
                'info' => "New jobs will be added to this Pueue job group. To use the default group, leave this field empty.", //@translate
            ],
            'attributes' => [
                'id' => 'pueue_group',
                'required' => false,
            ],
        ]);
    }

    function isValid()
    {
        return parent::isValid(); // TODO: Change the autogenerated stub
    }
}